# Generated by Django 2.2.12 on 2020-10-03 19:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', django_mysql.models.EnumField(choices=[('in', 'in'), ('mm', 'mm'), ('oz', 'oz'), ('ml', 'ml'), ('each', 'each')], default='each')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.IntegerField(default=0)),
                ('unit_threshold', models.IntegerField(default=0)),
                ('vendor_url', models.URLField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
