# Generated by Django 2.2.12 on 2020-10-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
