# Generated by Django 2.2.12 on 2020-10-04 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_componentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.ComponentCategory'),
            preserve_default=False,
        ),
    ]
